@startuml
class Auftrag {
-Abo
-Rechnung
+Auftragszeilen
}
object Object01
object Object02
object Object03
object Object04
object Object05
object Object06
object Object07
object Object08

Object01 <|-- Object02
Object03 *-- Object04
Object05 o-- "4" Object06
Object07 .. Object08 : some labels

object Object11
object Object12
object Object13
object Object14
object Object15
object Object16
object Object17
object Object18

Object11 <|-- Object12
Object13 *-- Object14
Object15 o-- "4" Object16
Object17 .. Object18 : some labels
@enduml
