{
    'name': "itk_third_party_setup",
    'summary': "ITK third party setup. Installs all 3rd-party modules used by ITK.",
    'description': "ITK third party setup. Installs modules from Odoo App Store and OCA.",
    'author': "Alvarium Services, Andreas Väthröder, Fabian Väthröder",
    'website': "http://www.alvarium-services.de",
    'category': 'ITK - Specific Industry Applications',
    'version': '18.0.1.0.0',
    'depends': [
        'itk_base_setup',
        'hr_employee_firstname',
        'account_invoice_line_number',
        'partner_academic_title',
        # TODO: migrate & uncomment:
        # 'mass_editing',
        # 'mass_email_invoice',
        # 'web_sheet_full_width',
        # 'website_support',
        # 'website_support_analytic_timesheets',
        # 'website_support_billing',
        # 'purchase_order_line_number',
        # 'bi_crm_claim',
        # 'web_tree_resize_column',
        # 'web_no_bubble',
    ],
    'data': [],
    'installable': True,
    'application': False,
    'auto_install': False,
}
