{
    'name': "itk_projectcategory",
    'summary': "Project Category",
    'description': "ITK Projekt Kategorien",
    'author': "Alvarium Services, Andreas Väthröder, Fabian Väthröder",
    'website': "alvarium-services.de",
    'category': 'ITK - Specific Industry Applications',
    'version': '18.0.1.0.0',
    'depends': ['base', 'account'],
    'data': [
        'security/ir.model.access.csv',
        'views/account_invoice_views.xml',
        'views/projectcategory_views.xml',
        'data/itk_projectcategory.xml',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
    'auto_install': False,
}
