{
    'name': "ITK Basis-Einrichtung",
    'summary': "ITK base setup. Installs all modules used by ITK.",
    'description': "ITK base setup. Installs all modules used by ITK and delivered with the Odoo system setup.",
    'author': "Alvarium Services, Andreas Väthröder, Fabian Väthröder",
    'website': "http://www.alvarium-services.de",
    'category': 'ITK - Specific Industry Applications',
    'license': 'LGPL-3',
    'version': '18.0.1.0.3',
    'depends': [
        'base',
        'crm',
        'sale',
        'purchase',
        'hr',
        'hr_attendance',
        'hr_timesheet',
        'mass_mailing',
        'survey',
        'itk_crm',
        'itk_multifactor',
    ],
    'data': [
        'data/menu_contacts_config.xml',
        'views/res_partner_form.xml',
        'views/res_partner_list.xml',
        'views/res_partner_search.xml',
        'views/sale_subscription_line.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
