{
    "name": "ITK Helpdesk-Oberfläche",
    "summary": "Odoo-11-Helpdesk-Oberfläche, Menüs und Abläufe im Odoo 18 (website_support -> helpdesk_mgmt)",
    "version": "18.0.1.1.3",
    "license": "LGPL-3",
    "category": "Helpdesk",
    "author": "IT-Kommunal GmbH",
    "website": "https://www.it-kommunal.at",
    "depends": [
        "helpdesk_mgmt",
        "helpdesk_mgmt_timesheet",
        "itk_helpdesk_category_user",
        "website",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/helpdesk_channels.xml",
        "views/helpdesk_ticket_category_views.xml",
        "views/helpdesk_priority_views.xml",
        "views/helpdesk_subcategory_field_views.xml",
        "views/helpdesk_ticket_views.xml",
        "views/helpdesk_stage_views.xml",
        "views/helpdesk_tag_views.xml",
        "views/helpdesk_ticket_templates.xml",
        "views/helpdesk_public_templates.xml",
        "views/res_config_settings_views.xml",
        "views/menus.xml",
    ],
    "assets": {
    },
    "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
    "auto_install": False,
}
